[package]
name = "bcrypt"
version = "0.1.0"
authors = ["ysugimoto <sugimoto@wnotes.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bcrypt = "0.8"
