version: 2.1

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - setup_remote_docker
      - run: cargo install cross
      - run: make build
      - persist_to_workspace:
          root: .
          paths:
            - ./dist
            - ./tools
  publish:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: .
      - run:
          command: |
            sudo apt-get install jq file
            sh ./tools/github-release.sh

workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/

executors:
  default:
    docker:
      - image: circleci/rust
